// Generated by ts-to-zod
import { z } from "zod";

export const bottleSchema = z.object({
  id: z.number(),
  Producer: z.string(),
  Name: z.string(),
  Varietal: z.string(),
  Vintage: z.number(),
  VineyardLoc: z.string(),
  VineyardName: z.string(),
  Bin: z.string(),
  Purchased: z.string(),
  Consumed: z.string().optional(),
  Notes: z.string(),
});
