// Generated by ts-to-zod
import { z } from "zod";

export const bottleSchemaSchema = z.literal(z.infer);

export const bottleSchemaInputSchema = z.literal(z.input);

export const crudSchemaInputSchema = z.literal(z.input);

export const crudSchemaOutputSchema = z.literal(z.output);

const bottlesDBSchema = z.array(z.literal(z.infer));
