// Generated by ts-to-zod
import { z } from "zod";

import * as generated from "./main.d.zod";

export type BottleSchema = z.infer<typeof generated.bottleSchemaSchema>;

export type BottleSchemaInput = z.infer<
  typeof generated.bottleSchemaInputSchema
>;

export type CrudSchemaInput = z.infer<typeof generated.crudSchemaInputSchema>;

export type CrudSchemaOutput = z.infer<typeof generated.crudSchemaOutputSchema>;
